services:
  - type: web
    name: langams-umami
    env: docker
    repo: https://github.com/bnpd/umami.git
    region: frankfurt
    plan: free
    branch: main
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: umami-db
          property: connectionString
      - key: HASH_SALT
        generateValue: true

databases:
  - name: umami-db
    plan: free
    databaseName: umami
    user: umami
    region: frankfurt
